<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View a demo_illustration</name>
   <tag></tag>
   <elementGuidId>92a3f7b1-f0ff-4638-9980-dec474ac6cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.illustration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e41a663d-beb3-44f3-bd3e-4822f08e4cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>illustration</value>
      <webElementGuid>1298b718-ecc5-4b18-b5ca-8d770e837b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/testing_solutions/rebrand_2022/api_testing/what-is-api-testing.svg</value>
      <webElementGuid>12ec6f68-69cc-4bcc-ad21-dd1d9a7dc277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Feature illustration</value>
      <webElementGuid>3592eb98-d495-4115-906b-f01e87d2c5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;APITesting_wrapAPITesting__AKkWX&quot;]/div[@class=&quot;solution&quot;]/div[@class=&quot;features&quot;]/div[@class=&quot;listing&quot;]/div[@class=&quot;feature&quot;]/img[@class=&quot;illustration&quot;]</value>
      <webElementGuid>2dcfef11-6f1f-4a52-bca4-1209fba1ff95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>7405f9ff-4851-4b0a-9102-eb68a4b0380b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Feature illustration']</value>
      <webElementGuid>da0271d4-d1ea-46ad-bcb9-ad78153cc310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>78073426-dafb-4357-8ea2-fb3751d2fb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/testing_solutions/rebrand_2022/api_testing/what-is-api-testing.svg' and @alt = 'Feature illustration']</value>
      <webElementGuid>1b0e3d60-a206-463f-a4ee-19f00690edfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
