<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_News</name>
   <tag></tag>
   <elementGuidId>26997200-f448-4e1f-8d44-07f8c65939cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.category_item.news</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12432e8b-8f39-4925-bcb8-3b64bbab4649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_item news</value>
      <webElementGuid>fa7334ee-ecfe-4c65-a930-646a2372618b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active-category</name>
      <type>Main</type>
      <value>news</value>
      <webElementGuid>3cf3fc88-2a02-4ed1-b1e6-c997452c27ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>3dcc64dd-833e-45f1-a0fe-2e05b61c61c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;BlogCenter_wrapBlogCenter__9owve&quot;]/div[@class=&quot;wrap_top_nav&quot;]/div[@class=&quot;top_nav_category&quot;]/div[@class=&quot;category_item news&quot;]</value>
      <webElementGuid>d63f08ce-f427-4f39-ad6f-0072037cc6fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]</value>
      <webElementGuid>65dfc572-e46a-4f8d-af51-93228b871f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[1]</value>
      <webElementGuid>0a877bd7-3356-42aa-98e1-6261a619613b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::div[5]</value>
      <webElementGuid>62fd95fd-e59e-42f9-904c-ad1228424698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::div[1]</value>
      <webElementGuid>d03efc47-c2e8-4125-8b41-5dc32f90cd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insights'])[1]/preceding::div[2]</value>
      <webElementGuid>dbf6616f-7179-4c5e-a002-e04c970f3b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>63e4e8fd-60db-4212-8b0f-a2d9ee79ef2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'News' or . = 'News')]</value>
      <webElementGuid>bfb6acef-7040-490e-9928-d19f22a29352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
