<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>215070db-5971-461c-81a0-2ace0c292d49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item_blog.devops.item_page_1.active > a > div.img_feature_blog > img[alt=&quot;CI/CD Pipeline more code more tests&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='devops']/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>17460489-51b8-40ed-b626-51a37fca3e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cms-cdn.katalon.com/CD_Pipeline_more_code_more_tests_59457b6764.png</value>
      <webElementGuid>27fd9534-49d6-4a2e-88c7-4094f8e16f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CI/CD Pipeline more code more tests</value>
      <webElementGuid>dda0e9e2-df0c-442d-9d2a-ffa83a212c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>28f334d8-a420-4ef1-9f48-c4d416b2e1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;devops&quot;)/div[@class=&quot;blog_list&quot;]/div[@class=&quot;blogs&quot;]/div[@class=&quot;item_blog devops item_page_1 active&quot;]/a[1]/div[@class=&quot;img_feature_blog&quot;]/img[1]</value>
      <webElementGuid>316c659c-b1e4-456f-a5f1-54d41dbb85ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='devops']/div/div/div/a/div/img</value>
      <webElementGuid>7ea8eb39-c5c8-471f-a927-633e368fa43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='CI/CD Pipeline more code more tests'])[2]</value>
      <webElementGuid>412813c4-e53f-442a-80e0-aa7dc4fed41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/a/div/img</value>
      <webElementGuid>fe18ed90-8f17-4006-b6cd-4db941689365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cms-cdn.katalon.com/CD_Pipeline_more_code_more_tests_59457b6764.png' and @alt = 'CI/CD Pipeline more code more tests']</value>
      <webElementGuid>d48296a9-3936-40b2-b195-7420ae628d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
