<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accessibility Testing</name>
   <tag></tag>
   <elementGuidId>2f2416ed-b85d-4313-bdba-a2d87d157fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.categories > #accessibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='accessibility'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b7c4b92-995f-46ff-8311-f2857169bb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>914efa33-e195-4878-8c1d-cae67ef1b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accessibility</value>
      <webElementGuid>dd3e40cf-25d3-4174-bc1d-2d6521ebd487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessibility Testing</value>
      <webElementGuid>db80395e-d9e2-4131-9810-9324e185abd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Integrations_wrappingIntegrations__1xkjR&quot;]/div[@class=&quot;integrations&quot;]/div[@class=&quot;ecosystem&quot;]/div[@class=&quot;ecosystem-main&quot;]/div[@class=&quot;categories&quot;]/div[@id=&quot;accessibility&quot;]</value>
      <webElementGuid>f66d0c21-1bff-4d59-81fd-a76fc4e4a5ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='accessibility'])[2]</value>
      <webElementGuid>9a5d16b7-7927-4ce4-adc1-e35be9bed044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div[55]/div[2]/div[3]/div[2]</value>
      <webElementGuid>0c15209e-7ce9-49fe-9a33-54dcaef7456f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all'])[3]/following::div[1]</value>
      <webElementGuid>ab735695-2c29-41f6-962b-476a1456d805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual Testing'])[4]/following::div[4]</value>
      <webElementGuid>fac79159-cc12-4fad-a288-e7a3034ad385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALM &amp; Test Management'])[8]/preceding::div[1]</value>
      <webElementGuid>21bbc3dd-d3a0-43d4-b1fc-4213e1b17651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Testing'])[6]/preceding::div[2]</value>
      <webElementGuid>b93a604f-d1de-40a2-96a1-d44c66b3eebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[55]/div[2]/div[3]/div[2]</value>
      <webElementGuid>6cd5e428-ec25-4f83-9d80-f1f6e34c5ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'accessibility' and (text() = 'Accessibility Testing' or . = 'Accessibility Testing')]</value>
      <webElementGuid>d229e65d-9a32-484a-8f1a-64941b75f72c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
