<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Not appropriate</name>
   <tag></tag>
   <elementGuidId>a3c8ab88-b463-4281-9e8e-fd9c1008161f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.survey_answer_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b16bcb0b-41bf-43fa-80bd-aab8538002fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>survey_answer_button</value>
      <webElementGuid>702fe96d-044f-4cae-8270-2a537c8b91d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92ae4bd8-ed98-4b3c-bf88-45e7061d7e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not appropriate</value>
      <webElementGuid>6bbff762-64e1-4f52-9462-cb6493677e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_answers_wrapper&quot;)/button[@class=&quot;survey_answer_button&quot;]</value>
      <webElementGuid>0e7ef8ce-9f10-47ec-a7a0-5d4dc700025a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Demo_Objects_1/Page_DEMOQA/iframe_concat(id(, , d0a61c14, , ))_d0a61c14</value>
      <webElementGuid>7cf51d40-ef65-4f8c-b7a4-fad9a26daa0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>3d1ca864-8dfb-430b-bed9-fbd1376a8646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='survey_answers_wrapper']/button</value>
      <webElementGuid>213524c1-4c81-4226-8b86-bfbfdd8b5fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already purchased'])[1]/preceding::button[1]</value>
      <webElementGuid>67d1cd12-4301-44b2-afeb-3a18e05d95c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not interesting'])[1]/preceding::button[2]</value>
      <webElementGuid>d5d6b7ed-4d2b-4c9e-9a14-27280ea457e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not appropriate']/parent::*</value>
      <webElementGuid>99bd8143-c3d2-4eba-b18b-047214427d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>046c84d0-3024-4ebe-928e-8dafcb101247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Not appropriate' or . = 'Not appropriate')]</value>
      <webElementGuid>f658f45b-8435-4e6f-844d-00793aea244a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
