<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ad by_close_button_svg</name>
   <tag></tag>
   <elementGuidId>050fc733-133f-4ed4-9ebf-8fa644abb4a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close_button_svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='close_button_svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>533a2d0e-ff24-49d1-ad13-7997edbc2820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close_button_svg</value>
      <webElementGuid>fe3fe970-feb6-4c3e-bffe-45993e20975e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.criteo.net/flash/icon/close_button.svg</value>
      <webElementGuid>623019eb-e8a8-414f-8568-202c038ad9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close_button_svg&quot;)</value>
      <webElementGuid>00e3f392-8167-4464-bf9e-edb7a662254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Demo_Objects_1/Page_DEMOQA/iframe_concat(id(, , d0a61c14, , ))_d0a61c14</value>
      <webElementGuid>11b4b38e-b1f7-4fe0-b9ad-af295f087566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='close_button_svg']</value>
      <webElementGuid>bd24eaac-64d6-4034-8705-b5d438be2379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close_button']/img</value>
      <webElementGuid>32ea2421-7874-4984-92bb-4d1a9f71228c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.criteo.net/flash/icon/close_button.svg')]</value>
      <webElementGuid>4558998e-a258-43bc-87e1-705174585d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>70a0ea02-1740-4111-a45b-0fa14651647e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'close_button_svg' and @src = 'https://static.criteo.net/flash/icon/close_button.svg']</value>
      <webElementGuid>55ce7fc5-7c83-4fb3-b25d-4e6e73602ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
