<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Incorrect phone number</name>
   <tag></tag>
   <elementGuidId>af57c432-b60f-4a82-b049-2973a52189d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.a-alert-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='auth-error-message-box']/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>502eea44-934a-41d5-83df-6c9d894ca9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-alert-heading</value>
      <webElementGuid>593662c2-4b9a-4d0a-9fcb-201921ee9d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incorrect phone number</value>
      <webElementGuid>ccce4a76-d738-427f-9694-14453d229298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-error-message-box&quot;)/div[@class=&quot;a-box-inner a-alert-container&quot;]/h4[@class=&quot;a-alert-heading&quot;]</value>
      <webElementGuid>f70bd73d-0d08-4a2b-a395-2554abdedc19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auth-error-message-box']/div/h4</value>
      <webElementGuid>a47bb432-72db-4ccf-8ca3-cfb2b52a67cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We cannot find an account with that mobile number'])[1]/preceding::h4[1]</value>
      <webElementGuid>3809728c-2762-40d3-b6c9-0af6b147034b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passkey error'])[1]/preceding::h4[1]</value>
      <webElementGuid>2ee68117-7e63-458f-88b4-76a6b5530dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incorrect phone number']/parent::*</value>
      <webElementGuid>5512f8f2-8ae9-48c6-9ec0-46bee3abeb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>d9e391f4-97e0-4b2e-92a2-0519796b0e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Incorrect phone number' or . = 'Incorrect phone number')]</value>
      <webElementGuid>8af75768-611c-4917-8d44-5c8970647c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
