<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enterprise Account Manager (SaaS, Autom_47b0db</name>
   <tag></tag>
   <elementGuidId>c43224e0-a413-4b20-a427-566bcba4448f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.job_preview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/div/div/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d716d21a-0bd7-4b34-b25e-770f7c35be82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job_preview</value>
      <webElementGuid>4cabc564-101c-409e-91f6-9da33df56f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise Account Manager (SaaS, Automation Testing)</value>
      <webElementGuid>95ae6c96-7982-4325-9160-a3a51d691fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;searchbar_section&quot;]/div[@class=&quot;search_result&quot;]/a[1]/div[@class=&quot;job_preview&quot;]</value>
      <webElementGuid>660746d7-dd9d-47d2-a14e-1135a011df4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div/div[2]/a/div</value>
      <webElementGuid>739ecaa1-5d8a-4fcf-99db-d1b97a459eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='starts here'])[1]/following::div[5]</value>
      <webElementGuid>bb5400b4-f543-4d21-80ae-02802b2aae6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all jobs'])[1]/preceding::div[1]</value>
      <webElementGuid>cd977ec5-745a-412c-900f-e1a5dbc1a349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Katalon'])[1]/preceding::div[11]</value>
      <webElementGuid>a58f74b2-4b2b-4fde-87eb-373e40c417b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enterprise Account Manager (SaaS, Automation Testing)']/parent::*</value>
      <webElementGuid>04be0506-dc83-4293-8286-5518838a47b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/div/div/div[2]/a/div</value>
      <webElementGuid>0ba8c3e2-5744-412d-a1cc-5c1eb3def372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enterprise Account Manager (SaaS, Automation Testing)' or . = 'Enterprise Account Manager (SaaS, Automation Testing)')]</value>
      <webElementGuid>09dde6ad-02c1-4784-b511-d55ba86a4d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
