<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_starts here_input_job_search</name>
   <tag></tag>
   <elementGuidId>dc792e77-dd07-4a14-a931-d373e74caa0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input_job_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10acfb4c-3aec-4484-b235-953316892939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_job_search</value>
      <webElementGuid>c82d2f4d-1f37-498b-a4ca-24475d319eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for a career you love</value>
      <webElementGuid>5f47d552-ce16-436b-8b57-9d2f87d09fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;searchbar_section&quot;]/div[@class=&quot;search_input&quot;]/input[@class=&quot;input_job_search&quot;]</value>
      <webElementGuid>a237234d-0634-4f8c-b1c3-28cf832b1764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>117baab2-25a9-481c-b83a-d867f5afe7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div/div/div/input</value>
      <webElementGuid>52231a0c-be0c-4a1e-9aa2-c3b387964c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/input</value>
      <webElementGuid>853af60d-b810-4e5d-b30c-d256f7286ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search for a career you love']</value>
      <webElementGuid>bc00646c-7b25-4372-965c-109b555bc015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
