<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Standalone</name>
   <tag></tag>
   <elementGuidId>7a3d67a5-0483-410f-814e-e7c4beab7569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.package_selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97c9a866-cdc3-42b7-aa7e-30f875bb5aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>package_selected</value>
      <webElementGuid>ecd24a68-ffb8-484c-bd1a-e79f91b666f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standalone</value>
      <webElementGuid>5c566839-4c5b-4ff9-8b16-9fd2cf7f70f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__8APFW&quot;]/div[@class=&quot;pricing_block_section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;mobile_package_menu_section&quot;]/div[@class=&quot;package_menu_dropdown&quot;]/div[@class=&quot;package_selected&quot;]</value>
      <webElementGuid>6fc1b76b-bb21-432d-bb2f-e0ac3b0d2307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>678bf5f2-0e06-461d-b3fa-1ea1eb5af3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best value to get started with Katalon'])[1]/following::div[3]</value>
      <webElementGuid>4856e714-2dc0-4f35-8f45-42d66d6659fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starter Plan'])[1]/following::div[4]</value>
      <webElementGuid>f0bebf50-70d9-466b-ae04-f14ce2d6fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[5]/preceding::div[1]</value>
      <webElementGuid>d17ca66e-832f-4f72-a9d8-4b1989f8f018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standalone'])[3]/preceding::div[2]</value>
      <webElementGuid>d16b19b1-0246-4142-bb84-07077e54a5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>a8aa775f-38e9-4d90-834b-9f3230f5499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Standalone' or . = 'Standalone')]</value>
      <webElementGuid>d73cb4ea-0f25-4dec-8e76-f79c3e26b632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
