<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Compare plans</name>
   <tag></tag>
   <elementGuidId>b12b9568-ba24-4b6e-a51a-6aeb6ecc7e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.compare_plan_section > div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b88b752c-6e2a-46ec-a54d-4d1d9ad0260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>4058d299-f5c0-4f4a-827f-6061adb73952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare plans</value>
      <webElementGuid>721bd29a-7f0b-4eb1-a35c-8e8e9f6be1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__8APFW&quot;]/div[@class=&quot;compare_plan_section&quot;]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>c96364f3-f50f-4f0e-bea8-f56179b77bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[4]/div</value>
      <webElementGuid>915aea6b-9449-4193-8dd3-995dbece06c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted by enterprises worldwide'])[1]/following::div[21]</value>
      <webElementGuid>4fa57a42-6104-41ea-9269-f83f8665fe8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon TestCloud'])[3]/following::div[24]</value>
      <webElementGuid>f5a2a5ae-e069-42b2-bb08-5c6dbb175419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[6]/preceding::div[1]</value>
      <webElementGuid>c7ee58b1-dff3-463f-bd92-bd83bcecb31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for free'])[3]/preceding::div[2]</value>
      <webElementGuid>64b2e5d6-914a-4a4e-a3ea-7b2af00ac6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare plans']/parent::*</value>
      <webElementGuid>ce0f0a61-042f-484a-8db2-959f1d32406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>c500a742-cf83-4554-a940-61b5475993a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Compare plans' or . = 'Compare plans')]</value>
      <webElementGuid>565a29fe-af63-4713-9c42-840704ae3739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
