<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Starter Plan</name>
   <tag></tag>
   <elementGuidId>ec4c5613-9cf5-4d1f-ad56-a14df0cff7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.package_dropdown_item.starter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6f0c322-6420-4851-b84e-158251d1dc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>package_dropdown_item starter</value>
      <webElementGuid>aca13da5-8ee0-47b5-ba33-268799d87aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active-package</name>
      <type>Main</type>
      <value>starter</value>
      <webElementGuid>c8ea6117-fe85-4d02-ba14-ae51df08a150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Starter Plan</value>
      <webElementGuid>00e264c3-3b11-4c64-8e8c-a0ad65e7824e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__8APFW&quot;]/div[@class=&quot;pricing_block_section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;mobile_package_menu_section&quot;]/div[@class=&quot;package_menu_dropdown active&quot;]/div[@class=&quot;package_options&quot;]/div[@class=&quot;package_dropdown_item starter&quot;]</value>
      <webElementGuid>1e4bcda6-8557-4601-afc3-a78fa1fa6cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>2ca981bf-3ce1-48f1-9c76-dc6893f20579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standalone'])[3]/following::div[1]</value>
      <webElementGuid>c62fa792-b21b-42eb-bc3f-d2dc4ebb4917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[5]/following::div[2]</value>
      <webElementGuid>af85d7f7-fb99-4193-b7f0-4c0c04a84083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/preceding::div[1]</value>
      <webElementGuid>3cc43117-2175-4b7b-8078-001afbbdc970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic test automation for small teams or getting started.'])[1]/preceding::div[2]</value>
      <webElementGuid>62a92eab-02aa-4f00-9152-02ab9a90cb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>45a06b94-110c-4692-a83c-55e4b517bf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Starter Plan' or . = 'Starter Plan')]</value>
      <webElementGuid>3d933800-b911-4c0d-b5fe-29828e539014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
