<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_APPLY</name>
   <tag></tag>
   <elementGuidId>492ebb51-7382-44f1-89f9-33f9a2f24263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.applyBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a7537c0-3fd1-43c0-9f1a-7e6dce7f6ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa112daa-9216-46ef-8fbe-796032021021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>applyBtn</value>
      <webElementGuid>ba14cb0d-bdd1-43a6-93f4-2b9b35a62268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLY</value>
      <webElementGuid>14602ed2-5b93-4e57-87c8-0e3154f9cb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bgGradient webpSupport&quot;]/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40&quot;]/div[1]/div[@class=&quot;hdsw widgetOpen&quot;]/div[@class=&quot;hdsw_inner&quot;]/div[@class=&quot;hdsw_inputBox selectHtlCity inactiveWidget activeWidget grow-half&quot;]/div[@class=&quot;paxpicker-wrapper&quot;]/div[@class=&quot;btnContainer&quot;]/button[@class=&quot;applyBtn&quot;]</value>
      <webElementGuid>25ad92a7-d5ec-4c5b-ac30-78f6264a2b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b421828b-5a6c-4579-9c72-c599b315cf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[4]/div[3]/div[2]/button[2]</value>
      <webElementGuid>6e08e7ac-2d45-4bb7-84a0-6981b126012f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ ADD ANOTHER ROOM'])[1]/following::button[1]</value>
      <webElementGuid>7d90961f-8d7c-4d9f-9392-ceb436db4d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Below 12 Years'])[1]/following::button[2]</value>
      <webElementGuid>3601e5a9-46c7-473c-9b0c-7d2ee447060b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::button[1]</value>
      <webElementGuid>af1c2ecd-9ce7-4172-972c-e766cf6bb575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Filters (Optional)'])[1]/preceding::button[1]</value>
      <webElementGuid>b8b43388-425f-4092-a0df-5d65505c4cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPLY']/parent::*</value>
      <webElementGuid>168cb025-8da8-4ae5-9b28-a40d93e01ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>ce183d93-5629-43bb-ae58-c6eea28f801f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'APPLY' or . = 'APPLY')]</value>
      <webElementGuid>952fbe1a-8d54-40e3-955c-95d561ccb7fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
