<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Tools_tool_1</name>
   <tag></tag>
   <elementGuidId>121ec5de-c9be-4b32-955b-3e17bbfe3328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a8d59b7-e1d3-498c-acb6-e8e3c45477f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-2</value>
      <webElementGuid>45997a46-9b02-498b-83d0-e414244adec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>89f6dec7-c871-432c-b376-31507cbcdad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b8b8fb84-a69a-4754-a47d-2b4dd4dd1f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Selenium Webdriver</value>
      <webElementGuid>124f1ef0-890c-4318-bfdc-6c4cdcdc00d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-2&quot;)</value>
      <webElementGuid>e816f65e-7dc9-4eef-9d47-4b5673ffd524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-2']</value>
      <webElementGuid>84eebf17-e326-4965-a394-bb8f69949890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input[3]</value>
      <webElementGuid>5424e8b1-6381-4433-9844-7748b563b272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input[3]</value>
      <webElementGuid>cf7d9c13-0b4d-4987-b485-c9c34bab4159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-2' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>69ef6506-d380-4384-b917-f09c26c1af83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
