<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profession_profession</name>
   <tag></tag>
   <elementGuidId>b06a6869-164c-44ec-b107-a806a88f817a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profession-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profession-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35a3116a-2722-466c-83f7-beedd1f5cd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profession-0</value>
      <webElementGuid>666561cf-9c95-4096-a046-e4899038a36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profession</value>
      <webElementGuid>c04a7ea8-97e5-48fe-be66-c7298f339345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3f808fee-bd2b-42c0-a31f-c1e7b1de58c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Manual Tester</value>
      <webElementGuid>a97dca9d-ef1c-4f20-93ef-be8e9a3e7fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profession-0&quot;)</value>
      <webElementGuid>e33d15cb-d0f8-49c0-9fab-5262bd326dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profession-0']</value>
      <webElementGuid>25e407ca-a515-40b2-b44b-3e8c1c15519f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[20]/input</value>
      <webElementGuid>c6bcc504-b967-4e5d-87eb-5354bf4b0f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/input</value>
      <webElementGuid>83fff714-8b81-4f8d-a053-eeff72dbe722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profession-0' and @name = 'profession' and @type = 'checkbox']</value>
      <webElementGuid>bee112e9-eeb9-402e-bfe9-8f5b7fd7eb5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
