<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AsiaEuropeAfricaAustraliaSouth Ameri_982c86</name>
   <tag></tag>
   <elementGuidId>acafb832-6934-4572-b2b0-4d5a396d653e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continents</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='continents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce4ba9ca-a56f-405d-b3ae-dcbaecb6cfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>9c80cab4-f183-4e35-85a0-7ec6feb9b9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>5080c24f-0677-4f42-b44c-c8704f9be277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>deb488d0-c6de-440d-a303-ab14efc65144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica</value>
      <webElementGuid>de53461a-c83d-47af-9df9-50bbd0b70718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continents&quot;)</value>
      <webElementGuid>959209dd-f61b-47c5-a90d-326724c20ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='continents']</value>
      <webElementGuid>9e8d8760-39c5-4997-a284-64af2a8abbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[25]/div[2]/select</value>
      <webElementGuid>72dbb605-67e3-4eec-b8a2-18657adc2510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continents'])[1]/following::select[1]</value>
      <webElementGuid>dcee606c-fdd2-47e7-9522-acdbc23b0508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Tools'])[1]/following::select[1]</value>
      <webElementGuid>26f3a7d1-fe05-4537-b905-8620c11a0d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Commands'])[1]/preceding::select[1]</value>
      <webElementGuid>ad286bdd-da06-4014-8607-323e51ba9757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Image'])[1]/preceding::select[2]</value>
      <webElementGuid>8a3dfe13-4915-4b40-b157-425da4bdb429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>8b9f4efc-1987-4b1b-b748-62e229c21ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'continents' and @name = 'continents' and (text() = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica' or . = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica')]</value>
      <webElementGuid>7fe74593-39ca-4230-8c11-9bfd88c64ba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
