<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Web testing</name>
   <tag></tag>
   <elementGuidId>6ce68620-d067-4fd5-a06b-98636519a32f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/section[2]/div/div/div/ul/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ad19aec5-ce38-45c8-bc5a-0682a0da2122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>archive_cat_120</value>
      <webElementGuid>36645a14-bd22-4459-9945-e0058e635b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Web testing</value>
      <webElementGuid>59e3ae20-15ad-46fa-932c-d8f5c72bfe21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/section[@class=&quot;container container_customized archive-page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;sidebar-filter col col-12 col-md-3&quot;]/div[@class=&quot;filter-list&quot;]/ul[@class=&quot;sub-filter-list&quot;]/div[@class=&quot;filter-item&quot;]/label[1]</value>
      <webElementGuid>b06c18fc-eb84-4d09-aeab-107ded59fc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/section[2]/div/div/div/ul/div[2]/label</value>
      <webElementGuid>8bf54bcb-5b89-43da-b1a6-9b28a0378d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API testing'])[1]/following::label[1]</value>
      <webElementGuid>acbf1861-e51e-46dc-a1b6-4bfad257cb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Types of testing'])[1]/following::label[2]</value>
      <webElementGuid>1b654a79-f07a-4489-aec5-920ebfe1f90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oldest Item'])[2]/preceding::label[1]</value>
      <webElementGuid>e4d3f2c0-c356-48e8-86db-c60763b27ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest Item'])[2]/preceding::label[1]</value>
      <webElementGuid>30a67206-768a-4464-ba62-1b8ae8953c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web testing']/parent::*</value>
      <webElementGuid>9c457dde-7dfc-49d0-8ffc-b9137d2dd69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>653d1650-2251-4c36-907b-bd11c2ea9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Web testing' or . = ' Web testing')]</value>
      <webElementGuid>9838b87a-426f-4906-801a-de260da19dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
