<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Oldest Item</name>
   <tag></tag>
   <elementGuidId>551c0e56-8383-4140-bde9-476f8be82107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/section[2]/div/div[2]/div/form/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9f01fcde-61fd-4e50-9cd1-90cbf82581d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>oldest_first</value>
      <webElementGuid>5b5bfbf0-1c4c-4edd-9274-e50d293aa1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7b331727-e55c-4b9c-ab59-55cb917b7f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oldest Item</value>
      <webElementGuid>cf8a75ac-5640-4297-9723-87c224f02efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/section[@class=&quot;container container_customized archive-page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12 col-md-9&quot;]/div[@class=&quot;list-top&quot;]/form[@class=&quot;sort-form&quot;]/div[@class=&quot;nice-select submit-filter open&quot;]/ul[@class=&quot;list&quot;]/li[@class=&quot;option&quot;]</value>
      <webElementGuid>05edda35-573e-46e1-9add-1fd75fa9d7ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/section[2]/div/div[2]/div/form/div/ul/li[2]</value>
      <webElementGuid>d440639a-336e-425e-b7be-00c71958b445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest Item'])[3]/following::li[1]</value>
      <webElementGuid>5b2cac4d-e172-4c3f-baa9-65ba3a30c4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest Item'])[2]/following::li[2]</value>
      <webElementGuid>1eb950a7-f953-4d86-8145-24ae6ecee89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title (a-z)'])[2]/preceding::li[1]</value>
      <webElementGuid>5155d905-796b-4399-8db1-6fedbea38184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title (z-a)'])[2]/preceding::li[2]</value>
      <webElementGuid>0e2613f5-d90b-4e46-b88e-8c8e9d096da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/ul/li[2]</value>
      <webElementGuid>29440dfb-e5d2-452f-806b-97ca04e6a2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Oldest Item' or . = 'Oldest Item')]</value>
      <webElementGuid>416233b4-f882-4162-a96e-b1d4d8b028b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
