<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>59b257da-68d6-484e-b7da-1a575583ce78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._1_3w1N._3ZeGqx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[4]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71dd4d36-8ab7-4772-97c2-2e33740d2a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1_3w1N _3ZeGqx</value>
      <webElementGuid>e5437780-40d0-4d3e-a151-c9720edeb20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login?ret=/search%3Fq%3DShoes%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DGROCERY%26as-show%3Don%26as%3Doff</value>
      <webElementGuid>513ee5ab-b433-438c-a936-6a1fa08fbe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>2903e3c4-116a-425f-8d0d-844f20d01956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_2nQkPF _1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;go_DOp _2errNR&quot;]/div[@class=&quot;_28p97w&quot;]/div[@class=&quot;_1psGvi _3BvnxG&quot;]/div[1]/a[@class=&quot;_1_3w1N _3ZeGqx&quot;]</value>
      <webElementGuid>b9ecccc7-309e-4ddd-9a7d-e51253e50710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[4]/div/div/div/a</value>
      <webElementGuid>8205a85d-2837-47ea-b973-39b4199e766c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>9a3cc305-e36f-496d-87cd-5fe1c4d7efac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery to 560048'])[1]/following::a[1]</value>
      <webElementGuid>f4e072bf-b0b6-4f1d-84f0-9ae78a678fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>6bb3586d-9f55-4399-80f0-83f06e21b57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>5a571b40-5f29-4f45-ba35-9e8f8586a242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/login?ret=/search%3Fq%3DShoes%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DGROCERY%26as-show%3Don%26as%3Doff')]</value>
      <webElementGuid>0f00b137-2664-48aa-8e15-63ffbea2b678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a</value>
      <webElementGuid>2a518372-8a50-4bd3-b0d8-d3f3a5a456d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login?ret=/search%3Fq%3DShoes%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DGROCERY%26as-show%3Don%26as%3Doff' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>5c1ddd9a-975c-409f-be33-ec45749fc9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
