<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_katalon-studio</name>
   <tag></tag>
   <elementGuidId>81cacacf-97ae-4de0-b84d-34f36e220a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.url.fn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repository-container-header']/div/div/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18aec09c-058e-4356-a806-29ace7b64735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url fn</value>
      <webElementGuid>114503bd-bfda-485f-a461-5eac036fed2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>1f4153a7-0238-40c5-a174-327acc6e9208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-type</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>4a1a89c6-285b-494b-a588-74bcb77800e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-url</name>
      <type>Main</type>
      <value>/orgs/katalon-studio/hovercard</value>
      <webElementGuid>6f07ed79-44e0-4ffe-aab1-56c99fff5fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-click</name>
      <type>Main</type>
      <value>hovercard-link-click</value>
      <webElementGuid>a7e45664-2190-4bfd-b47e-c69aea538034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-dimensions</name>
      <type>Main</type>
      <value>link_type:self</value>
      <webElementGuid>6618a8cb-1e26-4b44-a8dd-d5616e4d66cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalon-studio</value>
      <webElementGuid>a47ef951-961b-4591-88d4-06f9280dcb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        katalon-studio
</value>
      <webElementGuid>c7a9fa10-a69a-4895-8c73-c352a62bb632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repository-container-header&quot;)/div[@class=&quot;d-flex flex-wrap flex-justify-end mb-3  px-3 px-md-4 px-lg-5&quot;]/div[@class=&quot;flex-auto min-width-0 width-fit mr-3&quot;]/div[@class=&quot;d-flex flex-wrap flex-items-center wb-break-word f3 text-normal&quot;]/span[@class=&quot;author flex-self-stretch&quot;]/a[@class=&quot;url fn&quot;]</value>
      <webElementGuid>0f0da529-b73c-478b-9423-029e700825ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repository-container-header']/div/div/div/span/a</value>
      <webElementGuid>48ad1cc7-1f21-486a-9ed2-646c1ba98765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'katalon-studio')]</value>
      <webElementGuid>554cbbac-cb37-42cb-8aad-be49bcddadeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload'])[3]/following::a[1]</value>
      <webElementGuid>8baa71df-2ff7-4037-aa78-dd956f6fe610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>315d8b30-7c35-469b-ba72-68a57fb89905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='docker-images'])[1]/preceding::a[1]</value>
      <webElementGuid>68000e5e-3355-4c30-9733-adf74c8a1a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='katalon-studio']/parent::*</value>
      <webElementGuid>2bb516a3-d893-42d3-9191-bcb9381577b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/katalon-studio')]</value>
      <webElementGuid>9055ec1c-47b8-4e70-8db0-8e0c5d6790c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/a</value>
      <webElementGuid>d53da08b-2742-4571-a446-9143345725fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/katalon-studio' and (text() = '
        katalon-studio
' or . = '
        katalon-studio
')]</value>
      <webElementGuid>21a2bf1f-0d68-4eda-a969-596143b7a046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
