<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SKIP</name>
   <tag></tag>
   <elementGuidId>f69ded70-e13e-452b-8b23-ee4daba26112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.skipBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepBtnWrapper']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1222cde8-eb12-4ae6-81c3-988c314c8cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skipBtn</value>
      <webElementGuid>25cf9269-309b-4226-8b42-86e08815e19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SKIP</value>
      <webElementGuid>3be47813-e344-4aa9-8b7a-bf3d3864712b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepBtnWrapper&quot;)/div[@class=&quot;btnWrap&quot;]/button[@class=&quot;skipBtn&quot;]</value>
      <webElementGuid>91164d79-1f3d-4674-9cfa-ca46b983fd9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepBtnWrapper']/div/button</value>
      <webElementGuid>59656ebd-31de-4650-be83-019ba7960163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/preceding::button[1]</value>
      <webElementGuid>11e6bee3-2af3-46cd-94de-e481c75bee7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SKIP']/parent::*</value>
      <webElementGuid>39bb3d22-25f4-4cfb-b817-45e45954f667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a9ea3858-6020-43f4-968b-f5f7c1cd7ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SKIP' or . = 'SKIP')]</value>
      <webElementGuid>3ec98b17-24a6-4c51-bebe-bca5d49f3f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
