<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_firstName</name>
   <tag></tag>
   <elementGuidId>afb16056-65dd-462c-9d3a-405161ccf75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47144ec4-efdc-4a01-ba21-39385bf95c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>390f37dd-aa91-4972-8701-b051cafb25f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>5d33e04e-f6d1-4061-b36a-45696b879e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c39a1c26-1172-4209-8468-8bb4a3547a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>height40 inputField </value>
      <webElementGuid>8e279b03-2c18-4376-9668-e5d12341fc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>8ef944ca-871e-479b-81d2-37b681699e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>486098ee-3ef4-4f0d-a945-fd233c11aa78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalpopup&quot;)/div[@class=&quot;modalContent&quot;]/div[@class=&quot;formContentWrapper&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;detailsBoxWrapper&quot;]/div[@class=&quot;userDetailsWrapper three&quot;]/div[@class=&quot;nameInputWrapper  firstName&quot;]/div[@class=&quot;makeFlex column&quot;]/input[@class=&quot;height40 inputField&quot;]</value>
      <webElementGuid>ac7c12f0-8719-4ed4-a685-6b0bb9adac61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
      <webElementGuid>42266d09-c4de-4af1-a669-23140ab8d396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalpopup']/div/div/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>ad6d4abd-c534-43dc-9ab3-5fe99d3c5124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>36bfda9b-ff38-47a4-aea1-91ff80f51cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstName' and @placeholder = 'Name']</value>
      <webElementGuid>f9f5e224-72f3-4465-9d71-4ba91ba9cfd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
