<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Community</name>
   <tag></tag>
   <elementGuidId>b6b5d026-b886-4275-83c6-cde6e8c9e306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus']/nav/div[3]/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8bb35ce9-6eab-4127-9ac1-0fb152d2f3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://forum.katalon.com/</value>
      <webElementGuid>77da514a-c05a-4f45-978e-8f8930ead351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>aa3a50c1-6e68-436c-8f95-0fa055e56620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>36e6c479-6895-4e05-a688-91d94497bc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu__link bar-items-text</value>
      <webElementGuid>574391b1-ae54-4d6c-a9b0-1ee8139aaf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Community</value>
      <webElementGuid>49cfff62-b78c-463e-a9f4-b36cc8db6a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus&quot;)/nav[@class=&quot;navbar navbar--fixed-top navbar-sidebar--show&quot;]/div[@class=&quot;navbar-sidebar&quot;]/div[@class=&quot;navbar-sidebar__items&quot;]/div[@class=&quot;navbar-sidebar__item menu&quot;]/ul[@class=&quot;menu__list&quot;]/li[@class=&quot;menu__list-item&quot;]/a[@class=&quot;menu__link bar-items-text&quot;]</value>
      <webElementGuid>8eb35b81-7560-491c-958d-330dcd94bb6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus']/nav/div[3]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>ceb7ee9f-2756-4961-9070-a4350a51fc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Community')])[2]</value>
      <webElementGuid>35d0e2ba-c780-4087-9355-852eca7db9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Developer docs'])[2]/following::a[1]</value>
      <webElementGuid>b25ff038-5b71-4d83-807d-df0dec7c4975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon docs'])[2]/following::a[2]</value>
      <webElementGuid>15199038-d9cb-486a-b75a-8afd4f50cd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academy'])[2]/preceding::a[1]</value>
      <webElementGuid>5deb6c7b-4824-4bc8-a61d-ad0161c7c290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start now'])[2]/preceding::a[2]</value>
      <webElementGuid>59819991-121f-4661-9819-0983a388028b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://forum.katalon.com/')])[2]</value>
      <webElementGuid>0418d59b-0e4e-4e2e-be81-a5343b024778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>9fa14be1-1690-4362-a3d0-1ca70c96183e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://forum.katalon.com/' and (text() = 'Community' or . = 'Community')]</value>
      <webElementGuid>292bb7ea-ab17-49f7-9bb1-04f0af0ae3c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
