<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>38811bf4-4cef-4d75-adc8-47e093513cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>e681b0d5-80e9-4753-8fc2-846db4f1620d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>60664723-3641-432f-979e-e0011253ae81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>0873d7a6-4c2e-4843-b86b-6f3b6c2fb008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-miterlimit</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>caa74f11-9faf-4fe1-9b06-26b9cd33f8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c0ac53d8-fb25-4562-aa76-4b54a15e367d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M4 7h22M4 15h22M4 23h22</value>
      <webElementGuid>f7dfc443-1132-4ef1-a1c8-39489f6c7c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus&quot;)/nav[@class=&quot;navbar navbar--fixed-top&quot;]/div[@class=&quot;navbar__inner&quot;]/div[@class=&quot;navbar__items&quot;]/button[@class=&quot;navbar__toggle clean-btn&quot;]/svg[1]/path[1]</value>
      <webElementGuid>5c872a91-871b-4fec-a926-a6bf2ab663d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
