<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View all projects</name>
   <tag></tag>
   <elementGuidId>cb662597-436c-485d-8450-fb15249d4268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.p-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66b5aa3f-a1cd-4252-bfe4-633999d2d5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackid</name>
      <type>Main</type>
      <value>view-all-projects</value>
      <webElementGuid>7abae18d-93e4-4378-ab34-962e38c81520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/api/v1/katone/page/admin/organization/1202642/teams/projects</value>
      <webElementGuid>0a3ecf79-e537-48b7-b76c-c3d536696eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>7b5a8d08-fa60-4eed-9787-6e290d2516e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-groupid</name>
      <type>Main</type>
      <value>access-report</value>
      <webElementGuid>077ef722-2230-4db6-a58c-baa45bf413f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View all projects</value>
      <webElementGuid>813c8871-d32b-44eb-8f1d-f74e3ebbbf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;main-body-wrapper&quot;]/div[@class=&quot;main-body&quot;]/div[@class=&quot;d-flex align-items-start&quot;]/a[@class=&quot;p-0&quot;]</value>
      <webElementGuid>d489e6b4-bf48-4a37-be60-50c173664a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/a</value>
      <webElementGuid>0f91336e-c9a8-49b2-96c3-3dceef714279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View all projects')]</value>
      <webElementGuid>74d90915-f1d2-4d34-9d6c-b0af9ada559c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Projects'])[1]/following::a[1]</value>
      <webElementGuid>d8ee6720-aaff-42a9-9fb2-2f943a186e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Automation_Gajenda=ra'])[1]/following::a[1]</value>
      <webElementGuid>557049d1-97ee-4a1a-8c1a-829acc82f2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::a[1]</value>
      <webElementGuid>ffa583d2-f21a-4147-b6b6-5631c41fc228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all projects']/parent::*</value>
      <webElementGuid>536ef5ec-786c-4f78-8551-14ff78dbd64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/api/v1/katone/page/admin/organization/1202642/teams/projects')]</value>
      <webElementGuid>7341baa4-d3b1-41c2-b8d1-4d138f9ce62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>3d0ad994-5c61-45a8-a10f-ccc39a910955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/api/v1/katone/page/admin/organization/1202642/teams/projects' and (text() = 'View all projects' or . = 'View all projects')]</value>
      <webElementGuid>ea8f89ba-6cc2-43c2-9802-58bd309b8153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
