<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ENERGY</name>
   <tag></tag>
   <elementGuidId>133a7cf6-f79b-4e3a-81e6-3be4b350560c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content > div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[2]/div/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bbd1e36-004e-4b21-9777-72185a19933a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>88109f33-7cec-4e8c-94ae-c62cddb185ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENERGY</value>
      <webElementGuid>fa2b3f6a-d56e-4561-b2b4-dc0ae938e1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;CaseStudies_wrapCaseStudies__ShDnH&quot;]/div[@class=&quot;case-studies&quot;]/div[@class=&quot;customer-stories&quot;]/div[@class=&quot;listing&quot;]/a[@class=&quot;customer-story&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>d1ec64dd-d7a5-41c8-9219-08f86a603ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/div/a/div/div</value>
      <webElementGuid>2cbcec36-4394-422a-9578-ed2106b93ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a demo'])[1]/following::div[4]</value>
      <webElementGuid>4564c157-d9c5-4782-af68-08ab78cec9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success Stories'])[2]/following::div[21]</value>
      <webElementGuid>26b60b44-20da-4d73-bcd7-30be3eb54d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMUNICATION SERVICES'])[1]/preceding::div[2]</value>
      <webElementGuid>52730d14-0cbe-48ac-ae1e-7c8d8c63ae2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINANCIALS'])[1]/preceding::div[5]</value>
      <webElementGuid>592f5be4-86e5-4740-a34e-167714e80089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENERGY']/parent::*</value>
      <webElementGuid>7da99ab2-1921-48e3-a609-29e66436ff14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a/div/div</value>
      <webElementGuid>d1cbf6f0-ae16-40ca-8531-690da4c367e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ENERGY' or . = 'ENERGY')]</value>
      <webElementGuid>b6df68e4-b992-4f09-b152-6a817f2f8e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
