<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Headsets</name>
   <tag></tag>
   <elementGuidId>e8cf6476-82b8-473b-85a9-54117ccc6a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-size-small.a-color-base.truncate-2line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Gaming accessories'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ffb5b95b-3b92-4232-b67c-a0f65610afdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-small a-color-base truncate-2line</value>
      <webElementGuid>b1c7f9ab-8295-4adb-b4ef-641b602f3270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Headsets</value>
      <webElementGuid>a8435f96-7527-45d0-a240-93e06a1d316a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;V0HHparrihoYkHzcQceCAw&quot;)/div[@class=&quot;a-cardui-body&quot;]/div[@class=&quot;a-section a-spacing-small grid-row-1&quot;]/div[@class=&quot;a-section a-spacing-none quadrant-container quadrant-container-0&quot;]/a[@class=&quot;a-link-normal image-redirect aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none image-label aok-inline-block aok-align-center&quot;]/span[@class=&quot;a-size-small a-color-base truncate-2line&quot;]</value>
      <webElementGuid>2e598063-b16b-4afa-90b5-bfd172d25ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='V0HHparrihoYkHzcQceCAw']/div[2]/div/div/a/div[2]/span</value>
      <webElementGuid>ea1681de-0c23-48f2-96f2-e5486858ab1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gaming accessories'])[1]/following::span[1]</value>
      <webElementGuid>e6f14ddf-bbdd-4cab-8e0f-48a7d91b7763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to go to amazon.in'])[1]/following::span[1]</value>
      <webElementGuid>334d590e-a600-484e-83f3-d24c8a2f9421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboards'])[1]/preceding::span[1]</value>
      <webElementGuid>68ea9699-312a-470d-a20e-f5b2688cbf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer mice'])[1]/preceding::span[2]</value>
      <webElementGuid>cd7eb098-d8b0-4d4a-9704-4c2031584863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Headsets']/parent::*</value>
      <webElementGuid>d7575912-9ee1-4e8f-8728-1172249602e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/a/div[2]/span</value>
      <webElementGuid>cdeb8c01-c922-4f90-85e4-6635ce569a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Headsets' or . = 'Headsets')]</value>
      <webElementGuid>fcc50a51-5ef2-42ad-803e-3532e0928d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
