<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KataMeet</name>
   <tag></tag>
   <elementGuidId>46ec3edf-caac-45a7-a054-1fa920de869e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b96a1bae-ae34-4822-927a-294aae903919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>event_category_item</value>
      <webElementGuid>b5ea8a34-e0bd-4cb9-aefa-36660b935739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category-active</name>
      <type>Main</type>
      <value>kata_meet</value>
      <webElementGuid>8d883a51-89f8-4cf4-8c63-375906e001d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KataMeet</value>
      <webElementGuid>5d85d510-549d-40a4-bc0f-358c6114a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;WebinarCenter_wrapWebinarCenter__75n2i&quot;]/div[@class=&quot;all_event_section&quot;]/div[@class=&quot;event_category webinars active&quot;]/div[@class=&quot;event_category_item&quot;]</value>
      <webElementGuid>32c8a995-44f0-4bec-8d66-44cc9e416dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[4]</value>
      <webElementGuid>f46ed9ef-3dab-487e-a397-1bae8356a18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Co-hosted'])[1]/following::div[1]</value>
      <webElementGuid>9ea0af74-cf00-4c7e-a30a-99e572a23e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product release'])[1]/following::div[2]</value>
      <webElementGuid>f6fe0b34-b1af-47bd-9db0-4df1149ac2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conference'])[1]/preceding::div[1]</value>
      <webElementGuid>8db01c5b-f3da-4931-8c93-b00dfa84ed88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self-host'])[1]/preceding::div[2]</value>
      <webElementGuid>6cb99a94-7bc5-42d7-ad5d-b11d725b8af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KataMeet']/parent::*</value>
      <webElementGuid>9bec407d-3baa-46e5-91ef-3ece54bdf980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[4]</value>
      <webElementGuid>3df04450-596b-4501-a72b-0f7f89bf485c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KataMeet' or . = 'KataMeet')]</value>
      <webElementGuid>5c0d877f-a1dd-4d5d-b65f-eddeea3842ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
