<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Series</name>
   <tag></tag>
   <elementGuidId>c84ea54c-7053-4c09-bb2b-1050e4daa716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.event_category.webinars.active > div.event_category_item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0eca37fa-0990-4f76-a149-8ab9e72c04a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>event_category_item</value>
      <webElementGuid>5f0e852e-ba48-4107-aec6-dca4fbe4e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category-active</name>
      <type>Main</type>
      <value>series</value>
      <webElementGuid>8b01c657-87f1-470b-889d-c268ea658563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Series</value>
      <webElementGuid>2f9338bc-c672-45ce-8a30-1bad912dda57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;WebinarCenter_wrapWebinarCenter__75n2i&quot;]/div[@class=&quot;all_event_section&quot;]/div[@class=&quot;event_category webinars active&quot;]/div[@class=&quot;event_category_item&quot;]</value>
      <webElementGuid>b80d7743-259c-4c4f-b444-9462723b81fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>8cb3800c-25b9-4b72-83f3-57a344bda90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding series'])[1]/following::div[1]</value>
      <webElementGuid>16be2d51-70d2-4e44-9a10-b5c42c8fd8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[5]/following::div[3]</value>
      <webElementGuid>6e6ea3bc-c507-4a5d-a764-aed10a7ae40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product release'])[1]/preceding::div[1]</value>
      <webElementGuid>fdf78e09-e9fc-49fe-82a3-d452c8dd7480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Co-hosted'])[1]/preceding::div[2]</value>
      <webElementGuid>143b284b-2904-48df-b9b7-2f688d7b8847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Series']/parent::*</value>
      <webElementGuid>c59c2ebe-37bb-4c55-b7ad-e3a7bb5fd153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>159ed0ef-e31b-4098-aa4c-25c7c7a5bb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Series' or . = 'Series')]</value>
      <webElementGuid>4900d0c5-de3d-41dd-8dda-7c3f3e3cf05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
