<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>6b5ac5f2-78d7-4a8f-95b0-ae3f40b40e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._6WOcW9._3YpNQe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div[6]/a/div[2]/div[2]/div[2]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2c08f64-2363-4bd0-b5ab-018463b27ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6WOcW9 _3YpNQe</value>
      <webElementGuid>18de0d91-b24c-4460-98a7-7b399f31e2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.flipkart.com/grocery/dairy-eggs/dairy/pr?sid=73z,esa,dt6&amp;otracker=categorytree&amp;marketplace=GROCERY&amp;fm=neo%2Fmerchandising&amp;iid=M_3934a6ef-99f4-4a7f-8b61-452a3becb796_2_G211C67CJ4GB_MC.OWYMNIINR533&amp;otracker=clp_rich_navigation_1_2.navigationCard.RICH_NAVIGATION_Dairy+%2526+Eggs~Dairy~All_grocery-supermart-store_OWYMNIINR533&amp;otracker1=clp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=OWYMNIINR533</value>
      <webElementGuid>bf409747-741d-4a62-a26b-c7fc854fca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>4f9faedb-40d0-4108-8de2-95a85f85e6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn _2tvxW&quot;]/div[@class=&quot;InyRMC _3Il5oO&quot;]/div[@class=&quot;_37M3Pb&quot;]/div[@class=&quot;eFQ30H&quot;]/a[1]/div[@class=&quot;_1psGvi SLyWEo&quot;]/div[@class=&quot;ZEl_b_ _3joddx _3oFy_u _23xUYh _3pAV4E&quot;]/div[@class=&quot;_3_Fivj&quot;]/div[@class=&quot;_1y9fNR&quot;]/div[@class=&quot;_2IjXr8&quot;]/div[@class=&quot;_3XS_gI&quot;]/a[@class=&quot;_6WOcW9 _3YpNQe&quot;]</value>
      <webElementGuid>fd2e0719-fe95-4847-a906-0e53cef9d968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div[6]/a/div[2]/div[2]/div[2]/div/div/div[2]/a</value>
      <webElementGuid>d3b8e4e9-b601-4bab-9f68-301bc8880ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All')]</value>
      <webElementGuid>b91d276f-e818-4d79-9a72-fc3196e1c5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more in Dairy'])[1]/following::a[1]</value>
      <webElementGuid>80a64f00-9670-4d18-aabe-62c520dbc9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eggs'])[1]/following::a[1]</value>
      <webElementGuid>d8debd23-f723-4bd4-9e2b-22c145e69c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Milk'])[1]/preceding::a[1]</value>
      <webElementGuid>058077e9-7423-44d2-92a2-33c083fb910a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flavoured Milk'])[1]/preceding::a[2]</value>
      <webElementGuid>8736f8b7-3100-43be-bb21-b5fb8900cca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>11063ab3-ae7a-44bb-82fe-4bd7941d1cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.flipkart.com/grocery/dairy-eggs/dairy/pr?sid=73z,esa,dt6&amp;otracker=categorytree&amp;marketplace=GROCERY&amp;fm=neo%2Fmerchandising&amp;iid=M_3934a6ef-99f4-4a7f-8b61-452a3becb796_2_G211C67CJ4GB_MC.OWYMNIINR533&amp;otracker=clp_rich_navigation_1_2.navigationCard.RICH_NAVIGATION_Dairy+%2526+Eggs~Dairy~All_grocery-supermart-store_OWYMNIINR533&amp;otracker1=clp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=OWYMNIINR533')]</value>
      <webElementGuid>2a087c0a-22d3-44e6-857c-253af700b469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/a</value>
      <webElementGuid>6d4ec194-c7a3-4723-bf5d-311a70415188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.flipkart.com/grocery/dairy-eggs/dairy/pr?sid=73z,esa,dt6&amp;otracker=categorytree&amp;marketplace=GROCERY&amp;fm=neo%2Fmerchandising&amp;iid=M_3934a6ef-99f4-4a7f-8b61-452a3becb796_2_G211C67CJ4GB_MC.OWYMNIINR533&amp;otracker=clp_rich_navigation_1_2.navigationCard.RICH_NAVIGATION_Dairy+%2526+Eggs~Dairy~All_grocery-supermart-store_OWYMNIINR533&amp;otracker1=clp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=OWYMNIINR533' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>51371efc-3f36-4715-aa7e-6a19c2a1a33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
