<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>be41c04c-bec4-4d8e-b198-da355542d7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/div[3]/div/div[2]/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ba73d55-c351-40b9-9e4d-651b3ff02566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://academy.katalon.com/dashboard/logout</value>
      <webElementGuid>de594639-d93f-4594-9679-950ce33725e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Logout </value>
      <webElementGuid>56b56934-48dd-4336-a978-e3d2bf7ccaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;tutor-wrap tutor-dashboard tutor-dashboard-student&quot;]/div[@class=&quot;tutor-container&quot;]/div[@class=&quot;tutor-row&quot;]/div[@class=&quot;tutor-col-3 tutor-dashboard-left-menu&quot;]/ul[@class=&quot;tutor-dashboard-permalinks&quot;]/li[@class=&quot;tutor-dashboard-menu-logout&quot;]/a[1]</value>
      <webElementGuid>f0edef24-fe1d-43b8-abd6-1112066f645b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[3]/div/div[2]/div/ul/li[5]/a</value>
      <webElementGuid>d21d6fe8-a019-400f-922a-2f7ebb2d6253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>ae60fc6d-5162-4eb6-8212-506549a0a034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Quiz Attempts'])[2]/following::a[1]</value>
      <webElementGuid>7d070673-d32e-4839-a489-6e0fca256e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrolled Paths'])[2]/following::a[2]</value>
      <webElementGuid>0cefb2e1-5fda-4e09-ac29-e6b5f3b747f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Certifications'])[1]/preceding::a[1]</value>
      <webElementGuid>cf534035-08f4-4fe0-b471-4a90d9339064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progress Tracking'])[1]/preceding::a[1]</value>
      <webElementGuid>2eb823ee-177e-4080-8111-e4b4292df18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>79356411-440f-44fe-81a3-2dff9df50dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://academy.katalon.com/dashboard/logout')])[2]</value>
      <webElementGuid>9a1136a3-9cb5-468a-9812-3465a3e605fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[5]/a</value>
      <webElementGuid>e864eb14-70d5-467b-b7d9-ed8e81f9d194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://academy.katalon.com/dashboard/logout' and (text() = ' Logout ' or . = ' Logout ')]</value>
      <webElementGuid>693c2f8e-8a93-4c38-ac8e-79a71ecf62a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
