<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Security</name>
   <tag></tag>
   <elementGuidId>851f99c5-20a9-4863-b3bb-c10250747c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/footer/div/div/div[2]/div[2]/div[2]/div[2]/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>376cb5bb-7f64-45b5-9f87-45b9d2f96e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block px-2 xl:px-3 last:pr-0 text-sm text-neutral-800 hover:text-lilac-600</value>
      <webElementGuid>efa730ce-55b8-49fc-a5e7-de21c129e8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://katalon.com/security/</value>
      <webElementGuid>90ae1f02-b775-41c2-bc29-2d1d4d10bb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Security</value>
      <webElementGuid>8736c525-578a-4202-acb4-08c14abf757b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/footer[1]/div[@class=&quot;tw-newbrand22&quot;]/div[@class=&quot;container font-sans mx-auto px-4 x:px-0 md:flex&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2&quot;]/div[2]/div[@class=&quot;text-right mb-4 whitespace-nowrap overflow-auto md:overflow-hidden&quot;]/a[@class=&quot;inline-block px-2 xl:px-3 last:pr-0 text-sm text-neutral-800 hover:text-lilac-600&quot;]</value>
      <webElementGuid>9956fa88-1a02-40f5-a502-a21c666715bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/footer/div/div/div[2]/div[2]/div[2]/div[2]/a[4]</value>
      <webElementGuid>99eeda3c-a752-4db1-beb4-5e215ec301fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Security')]</value>
      <webElementGuid>23664226-2da5-4aa4-a7b2-5f80c6b6bd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Agreement'])[1]/following::a[1]</value>
      <webElementGuid>ab457b3b-6f45-4d5d-a2d6-67a1fd1f56d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::a[2]</value>
      <webElementGuid>4737053a-6c54-49c1-b788-9293c3d377be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up now'])[1]/preceding::a[1]</value>
      <webElementGuid>7788ce5d-6595-48fb-ab90-24046c6c0c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Security']/parent::*</value>
      <webElementGuid>0fc17651-d9fa-441c-971b-cbf67697b2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://katalon.com/security/')]</value>
      <webElementGuid>5e9fe97a-4e93-4458-8ccb-ad6dfaffdf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[4]</value>
      <webElementGuid>f3970dd0-2587-42e0-a08a-3412947e2e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://katalon.com/security/' and (text() = 'Security' or . = 'Security')]</value>
      <webElementGuid>47d0184e-bb10-4654-b88a-f2d22abf4aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
