<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>37d76351-9e2f-4b53-bea7-114b6f999e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;toggle-menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-img-header-mobile']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e2e8c8bc-7178-4c80-8c77-cf2cc6864f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>toggle-menu</value>
      <webElementGuid>287c460c-4329-4a62-a35c-ae7bb3ebce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg</value>
      <webElementGuid>f19c9517-8fbc-47c4-b85a-924510c6fa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-img-header-mobile&quot;)/img[1]</value>
      <webElementGuid>9b7a4fd6-662a-4069-808f-12174257c5cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-img-header-mobile']/img</value>
      <webElementGuid>7f9a33f7-a9de-43c1-9f75-6c89aa96f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='toggle-menu']</value>
      <webElementGuid>c857e4aa-0a8c-4944-8b16-9172a18e006f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>9aaed1d8-1b20-41d1-9b59-4f614c388fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'toggle-menu' and @src = 'https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg']</value>
      <webElementGuid>8551199d-b443-4bd3-a0f7-355db5120215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
