<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in to Katalon Academy_log</name>
   <tag></tag>
   <elementGuidId>b29fa47d-6d58-4022-82b3-845c44ffe42b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8cb085b-5a79-4b15-8cc2-208d8fdcfd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63552b13-efa4-4df5-b2bc-30e336f5404f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>7c16dbaf-f8bf-49bc-9e9b-32bf28af449b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>log</value>
      <webElementGuid>3f65919d-3f8d-4b9f-96b2-295d5fc5861c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_login</value>
      <webElementGuid>3c3fba20-c581-46c3-bd52-ad18dfb0a2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>733463bb-6b6e-46b1-91a8-8adda43b5454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f4e2cda9-271b-457d-b74a-175d938a9afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;tutor-wrap tutor-page-wrap post-7 page type-page status-publish hentry&quot;]/div[@class=&quot;tutor-template-segment tutor-login-wrap&quot;]/div[@class=&quot;tutor-template-login-form&quot;]/div[@class=&quot;tutor-login-form-wrap&quot;]/form[@id=&quot;loginform&quot;]/p[@class=&quot;login-username&quot;]/input[@id=&quot;user_login&quot;]</value>
      <webElementGuid>139b7a75-5aa8-4a00-9e9c-712a7ad19409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_login']</value>
      <webElementGuid>d7bfe492-0f6e-4e0e-8e78-addfe5c704a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/p/input</value>
      <webElementGuid>fc90bbaa-104f-405f-8045-483248198596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>8eb4b3d3-9849-4c02-b11e-2bcefd30816c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email' and @name = 'log' and @id = 'user_login']</value>
      <webElementGuid>d3d990df-a110-437f-8c00-78de93c27246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
