<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Visibility</name>
   <tag></tag>
   <elementGuidId>90c69a27-ad6a-4e88-8d72-65c2bf491fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='visibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>a969c822-02d4-49a1-8595-953e179ce884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-statement-text</value>
      <webElementGuid>760f1a90-3fd9-4794-9359-c4f5ac5fb502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visibility</value>
      <webElementGuid>d3c6e7de-9e5c-4ad6-921a-ae58b74de94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visibility</value>
      <webElementGuid>e1817992-6a82-427c-a2d5-55b1082d7412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibility&quot;)</value>
      <webElementGuid>dec5a0d8-fa5b-4808-a6d0-5950cf6e0fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='visibility']</value>
      <webElementGuid>cebb4911-bc8c-47d0-a9e1-7801a8190de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visibility-row']/div/div/h3</value>
      <webElementGuid>3b5cf2ed-223b-4c68-a948-59c689574871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Achieving software quality at scale'])[1]/following::h3[1]</value>
      <webElementGuid>d832bd68-d503-447e-8673-aa6d60407efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How Katalon accelerates the agile software development process'])[1]/following::h3[1]</value>
      <webElementGuid>dabb04e0-130c-466a-8741-79ff912c73da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scalability'])[1]/preceding::h3[1]</value>
      <webElementGuid>488dfe24-dad8-4e74-a006-99938e0cbd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speed'])[1]/preceding::h3[2]</value>
      <webElementGuid>a48445f2-83af-4764-87f1-73e261f7f81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>b6c20912-22d9-48fb-875b-a004c2d4c2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'visibility' and (text() = 'Visibility' or . = 'Visibility')]</value>
      <webElementGuid>32223c21-2c41-4969-89af-1566fabfa466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
