<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Affordability_accordion-arrow</name>
   <tag></tag>
   <elementGuidId>090cbc5c-de26-4025-aca9-d358f2f329d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lowcost-row > div.accordion-statement > div.accordion-header > img.accordion-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lowcost-row']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c8822e6-05a6-41e1-8f3e-9dfa42f70f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-arrow</value>
      <webElementGuid>431700f5-ef9e-438b-a9a0-fbf218c14cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg</value>
      <webElementGuid>8c810c14-65d5-414e-801e-88a938af05ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lowcost-row&quot;)/div[@class=&quot;accordion-statement&quot;]/div[@class=&quot;accordion-header&quot;]/img[@class=&quot;accordion-arrow&quot;]</value>
      <webElementGuid>2ae9ef29-695a-4f7c-9af6-38d3c1ea01c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lowcost-row']/div/div/img</value>
      <webElementGuid>35ece833-8648-42e1-beaa-9f2903fbd37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg')])[5]</value>
      <webElementGuid>2d6cb896-7241-481f-baa2-33375f4c6aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/img</value>
      <webElementGuid>20289dc4-120a-49b5-a7a1-961a6aeb98fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/business_outcome_2022/Plus.svg']</value>
      <webElementGuid>2fe13168-573b-497a-8e1a-c1ad0cfbb990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
