<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Articles-1</name>
   <tag></tag>
   <elementGuidId>8136dd3f-7d05-47eb-be15-eacd9e8ddc01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95a2a3d2-29f0-41f1-9e97-a93f77b582b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-grid slds-grid_align-spread slds-grid_vertical-align-center</value>
      <webElementGuid>f3247a10-5052-4561-b309-f9ef25bfd477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>96:1493;a</value>
      <webElementGuid>cb111177-df5b-40fc-ae10-22f970076ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Articles-1</value>
      <webElementGuid>601e5e2c-1d53-419f-98a1-2460a0505f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;null comm-page-global-search&quot;]/div[@class=&quot;themeLayoutStarterWrapper isHeroUnderHeader-false isHeaderPinned-false siteforceThemeLayoutStarter&quot;]/div[@class=&quot;body isPageWidthFixed-true&quot;]/div[@class=&quot;siteforceSldsOneColLayout siteforceContentArea&quot;]/div[@class=&quot;slds-col--padded contentRegion comm-layout-column&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/div[@class=&quot;forceCommunitySearch&quot;]/div[@class=&quot;slds-border_right slds-medium-size_1-of-6&quot;]/div[@class=&quot;scrollerWrapper slds-nav-vertical__section forceSearchScopesList&quot;]/div[@class=&quot;scopesBlock&quot;]/div[1]/ul[@class=&quot;scopesListSection slds-has-block-links--space&quot;]/li[@class=&quot;slds-nav-vertical__item forceSearchScopeItem&quot;]/a[@class=&quot;scopesItem slds-nav-vertical__action&quot;]/span[@class=&quot;slds-grid slds-grid_align-spread slds-grid_vertical-align-center&quot;]</value>
      <webElementGuid>9ab35421-32b9-4469-ac97-2b05b78374a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[3]</value>
      <webElementGuid>1bb9a5fc-b33a-4d48-8173-7ba06e6b07d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searchable objects from navigation bar'])[1]/following::span[5]</value>
      <webElementGuid>ae9530cd-141f-460f-8b5e-58d4032621f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/preceding::span[4]</value>
      <webElementGuid>b79bf228-a793-4cde-afb0-b397585ae56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>73f23c66-b47f-4cce-b3b5-07aeabb9a72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Articles-1' or . = 'Articles-1')]</value>
      <webElementGuid>de424dd2-858f-4704-a82f-830a8bc48461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
