<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Music</name>
   <tag></tag>
   <elementGuidId>19d12b1d-bed0-42c8-ae42-490867389f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>a706d5eb-114a-4d42-934f-45326e4f002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce7e1807-a03c-4e48-a51f-a140f69af7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-chip-cloud-chip-renderer</value>
      <webElementGuid>254cdaa4-cf4c-4b89-bebd-2284b6d3d8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Music</value>
      <webElementGuid>8b73059b-2e49-44a2-bac2-aaa95a4ae3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Music</value>
      <webElementGuid>df9148f2-70d8-4b18-9990-369815c1085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chips&quot;)/yt-chip-cloud-chip-renderer[@class=&quot;style-scope ytd-feed-filter-chip-bar-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>2ba64581-b780-45fe-b4cc-4b48821a1480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[2]</value>
      <webElementGuid>edd1d465-6895-4798-a5e3-65fda7b8b854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//iron-selector[@id='chips']/yt-chip-cloud-chip-renderer[2]/yt-formatted-string</value>
      <webElementGuid>1f4920de-fabb-4895-b818-7bbb8ee7d856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>137d1ff2-a2a6-44ca-9e63-6085eede0e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bollywood Music'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>0b19d8f2-a33d-4316-917d-e650a788ffa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantras'])[1]/preceding::yt-formatted-string[2]</value>
      <webElementGuid>34eb52bd-7998-4cf3-bf93-4cf2f2dab3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Music']/parent::*</value>
      <webElementGuid>c16e72c8-d6b6-40aa-a1c9-eed74feab004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-chip-cloud-chip-renderer[2]/yt-formatted-string</value>
      <webElementGuid>eafdedab-f842-4ca0-8f6f-2fe0e66f4af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and @title = 'Music' and (text() = 'Music' or . = 'Music')]</value>
      <webElementGuid>4c47e4aa-993b-40d7-b5b0-a06a76558f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
